### ISSUE TITLE
error :/usr/src/github.com/nknorg/nkn-file-transfer/common.go:109:18: undefined: vault.NewAccountWithPrivatekey

### ISSUE THREAD

**Issue by zsp042** [nknorg/nkn-file-transfer#10]
❯ go version
go version go1.13.8 linux/amd64
❯ go get -u github.com/nknorg/nkn-file-transfer

# github.com/nknorg/nkn-file-transfer
/usr/src/github.com/nknorg/nkn-file-transfer/common.go:109:18: undefined: vault.NewAccountWithPrivatekey
/usr/src/github.com/nknorg/nkn-file-transfer/common.go:120:52: account.PubKey().EncodePoint undefined (type []byte has no field or method EncodePoint)
/usr/src/github.com/nknorg/nkn-file-transfer/common.go:201:36: cannot use account (type *vault.Account) as type *nkn.Account in argument to nkn.NewClient
/usr/src/github.com/nknorg/nkn-file-transfer/common.go:201:77: cannot use nkn.ClientConfig literal (type nkn.ClientConfig) as type *nkn.ClientConfig in argument to nkn.NewClient
/usr/src/github.com/nknorg/nkn-file-transfer/common.go:202:6: cannot use seedNodeList["math/rand".Intn(len(seedNodeList))] (type string) as type *nkn.StringArray in field value
/usr/src/github.com/nknorg/nkn-file-transfer/common.go:211:26: client.OnBlock undefined (type *nkn.Client has no field or method OnBlock)
/usr/src/github.com/nknorg/nkn-file-transfer/common.go:216:10: invalid operation: <-client.OnConnect (receive from non-chan type *nkn.OnConnect)
/usr/src/github.com/nknorg/nkn-file-transfer/common.go:218:73: client.GetNodeInfo undefined (type *nkn.Client has no field or method GetNodeInfo)
/usr/src/github.com/nknorg/nkn-file-transfer/common.go:220:15: cannot range over client.OnConnect (type *nkn.OnConnect)
/usr/src/github.com/nknorg/nkn-file-transfer/common.go:221:75: client.GetNodeInfo undefined (type *nkn.Client has no field or method GetNodeInfo)
/usr/src/github.com/nknorg/nkn-file-transfer/common.go:221:75: too many errors
❯

**Comment by yilunzhang** [comment]
你可以看一下 readme 里面的第一段。这个 repo 是实验性质的，现在已经不再更新了。 nkn-sdk-go 里面的 Session 是我们最后推出的方案，在效率和稳定性上都比这个 nkn-file-transfer 要好得多，建议直接用 nkn-sdk-go （或者 nkn-sdk-js）里面的 Session 即可~
