### ISSUE TITLE
Using nkn file transfer question

### ISSUE THREAD

**Issue by lonnietc** [nknorg/nkn-file-transfer#11]
Hello,

I am trying to get a feel for how to use nkn-file-transfer on my Windows 10 (x64) with Go v1.19.3 for which I was able to compile it with not problems.

In the default start up, I used the below and want to run it in a terminal CLI mode if possible instead of via a browser.

```
file\test> .\nkn-file-transfer.exe -host
Creating 8 clients...
Client 7.3.1cbd6952514278e2d80cf5c23125bcf47ff9f57632e6cb90ced600c989a1240e connect to node 3.239.158.126:30002
Client 3.3.1cbd6952514278e2d80cf5c23125bcf47ff9f57632e6cb90ced600c989a1240e connect to node 57.128.70.98:30002
Client 6.3.1cbd6952514278e2d80cf5c23125bcf47ff9f57632e6cb90ced600c989a1240e connect to node 24.199.102.17:30002
Client 1.3.1cbd6952514278e2d80cf5c23125bcf47ff9f57632e6cb90ced600c989a1240e connect to node 157.230.56.217:30002
Client 5.3.1cbd6952514278e2d80cf5c23125bcf47ff9f57632e6cb90ced600c989a1240e connect to node 164.92.105.110:30002
Client 0.3.1cbd6952514278e2d80cf5c23125bcf47ff9f57632e6cb90ced600c989a1240e connect to node 159.65.83.60:30002
Client 2.3.1cbd6952514278e2d80cf5c23125bcf47ff9f57632e6cb90ced600c989a1240e connect to node 45.56.102.36:30002
Client 4.3.1cbd6952514278e2d80cf5c23125bcf47ff9f57632e6cb90ced600c989a1240e connect to node 159.223.172.181:30002
Created 8 clients
Start sender in host mode at 1cbd6952514278e2d80cf5c23125bcf47ff9f57632e6cb90ced600c989a1240e
```

As I see it here, I am connected to 8 neighbors and this is where I have a couple of questions.

1.) To use the nkn-file-transfer.exe, don't I need to have an nkn node running so that it can access the mesh network?

2.) If this is started in "host" mode then do I not need to have a directory for files to be shared so that the other nodes can access, get a directory of those files, and then download one or more?

3.) Where do I specify a directory to store the files on the "host" side?

4.) How do I get a directory of all files across all of the nodes that are in "host" mode so that I can choose one to download?

My thoughts were that this was more of a P2P file sharing that aggregates files from across all nodes running the nkn-file-transfer in host mode, but could be wrong here.

Please clarify so that I have better feel for how it is supposed to work.
Thanks

**Comment by lonnietc** [comment]
Is there any updates on how this is used?

In particular, I am interested in the "host/get" mode since I am assuming that the "host" allows the user to get a directory of available files and then "get" one that they want, but could be wrong.

Thanks

**Comment by yilunzhang** [comment]
This repo is deprecated since we now have better library (e.g. nkn-sdk-go) and ready to use software (e.g. nconnect). You might want to try https://github.com/nknorg/nconnect , it should work transparently with ssh or other tcp based file transfer app.

**Comment by lonnietc** [comment]
Thanks for letting me know about the depreciation of this library.  

While the nconnect seems to be good for tunneling and such, I actually need a core basic example on transferring files from one address to another because what I am seeking is to find and existing application, or try to develop one, that will be a type of P2P filesystem so that users can place files in a local directory on their PC and those files will be shared throughout the NKN network to others. 

I have been looking at various existing P2P filesystem solutions, but it may turn out that I may have to try and write something from scratch and was looking at the "nkn file transfer" as a possible base code to work with on this.

Is there another highspeed file transfer NKN CLI file transfer application around?

I may also need to figure out a type of database solution to integrate into it as well and maybe I can learn something from your chat or messaging examples.

Thanks again

**Comment by lonnietc** [comment]
UPDATE:  

I am actually looking at Surge now to see if maybe it can be used as a base to build what I am seeking to do.

```
https://github.com/rule110-io/surge
```

It seems to have many features that I want already and perhaps I can figure out the code and build it into this new type of system with a mountable virtual drive and also able to work with a local private testnet network as well.

Thanks agian.
